Models/ErrorViewModel.cs
namespace GofromaniaWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Opinie.cs
namespace GofromaniaWebApp.Models
{
    public class Opinie
    {

        public int Id { get; set; }
        public int Ocena { get; set; }
        public string Opinia { get; set; }
        public string Autor { get; set; }
        public string Ip { get; set; }
        public bool Aktwyne { get; set; }
        public string Admin { get; set; }
        public Opinie()
        {

        }
    }
}

Controllers/HomeController.cs
using GofromaniaWebApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GofromaniaWebApp.Controllers
{
    public class HomeController : Controller
    {
        

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Controllers/OpiniesController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GofromaniaWebApp.Data;
using GofromaniaWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace GofromaniaWebApp.Controllers
{
    public class OpiniesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OpiniesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Opinies
        
        public async Task<IActionResult> Index()
        {
              return View(await _context.Opinie.ToListAsync());
        }

        // POST: Active Opinies
        public async Task<IActionResult> ActiveOpinies()
        {
            return View(await _context.Opinie.Where(j => j.Aktwyne.Equals(true)).ToListAsync());
        }

        // GET: Opinies/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Opinie == null)
            {
                return NotFound();
            }

            var opinie = await _context.Opinie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (opinie == null)
            {
                return NotFound();
            }

            return View(opinie);
        }

        // GET: Opinies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Opinies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Ocena,Opinia,Autor,Ip,Aktwyne,Admin")] Opinie opinie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(opinie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ActiveOpinies));
            }
            return View(opinie);
        }

        // GET: Opinies/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            var userId = User.FindFirstValue(ClaimTypes.Name);
            ViewBag.userid = userId;


            if (id == null || _context.Opinie == null)
            {
                return NotFound();
            }

            var opinie = await _context.Opinie.FindAsync(id);
            if (opinie == null)
            {
                return NotFound();
            }
            return View(opinie);
        }

        // POST: Opinies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Ocena,Opinia,Autor,Ip,Aktwyne,Admin")] Opinie opinie)
        {
            if (id != opinie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(opinie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OpinieExists(opinie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(opinie);
        }

        // GET: Opinies/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Opinie == null)
            {
                return NotFound();
            }

            var opinie = await _context.Opinie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (opinie == null)
            {
                return NotFound();
            }

            return View(opinie);
        }

        // POST: Opinies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Opinie == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Opinie'  is null.");
            }
            var opinie = await _context.Opinie.FindAsync(id);
            if (opinie != null)
            {
                _context.Opinie.Remove(opinie);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OpinieExists(int id)
        {
          return _context.Opinie.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    
    
</div>

Views/Opinies/ActiveOpinies.cshtml
@model IEnumerable<GofromaniaWebApp.Models.Opinie>
<div class="row">
    <img src="~/img/baner.png" class="img-fluid" />
</div>
<div class="row" style="margin-top:200px;">
    <div class="col-sm-12">

    </div>
    <div class="col-sm-12">

    </div>
</div>
<div class="row text-center">
    <div class="col-sm-4 offset-sm-4">
        <h1>Gofromania</h1>
        <p>Powstała z miłości do pyszności i słodkości.</p>
        <p>Specjalizujemy się w wypiekaniu gofrów z najwyższej jakości składników z sezonowymi dodatkami od lokalnych dostawców.</p>
    </div>
</div>
<div class="row">
    <div class="col-sm-10 offset-sm-1">
        <div class="row">
            <div class="col-xl-2 col-md-3 col-sm-4 gallery-img">
                <img src="~/img/gallery/zdj1.jpg" class="img-fluid" />
            </div>
            <div class="col-xl-2 col-md-3 col-sm-4 gallery-img">
                <img src="~/img/gallery/zdj2.jpg" class="img-fluid" />
            </div>
            <div class="col-xl-2 col-md-3 col-sm-4 gallery-img">
                <img src="~/img/gallery/zdj3.jpg" class="img-fluid" />
            </div>
            <div class="col-xl-2 col-md-3 col-sm-4 gallery-img">
                <img src="~/img/gallery/zdj4.jpg" class="img-fluid" />
            </div>
            <div class="col-xl-2 col-md-3 col-sm-4 gallery-img">
                <img src="~/img/gallery/zdj5.jpg" class="img-fluid" />
            </div>
            <div class="col-xl-2 col-md-3 col-sm-4 gallery-img">
                <img src="~/img/gallery/zdj6.jpg" class="img-fluid" />
            </div>
            <div class="col-xl-2 col-md-3 col-sm-4 gallery-img">
                <img src="~/img/gallery/zdj7.jpg" class="img-fluid" />
            </div>
            <div class="col-xl-2 col-md-3 col-sm-4 gallery-img">
                <img src="~/img/gallery/zdj8.jpg" class="img-fluid" />
            </div>
            <div class="col-xl-2 col-md-3 col-sm-4 gallery-img">
                <img src="~/img/gallery/zdj9.jpg" class="img-fluid" />
            </div>
        </div>
    </div>
</div>
<div class="row" style="margin-top:100px;" name="mapa">
    <div class="col-sm-12 text-center"><h2>Czekamy na was w każdą niedzielę targową</h2></div>
</div>
<div class="row">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4073.863602909887!2d16.567533821913354!3d52.61781190565227!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47041700e03551e1%3A0xe60a4aca2202a40e!2sGofromania!5e0!3m2!1spl!2spl!4v1673173025417!5m2!1spl!2spl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>
<div class="row" style="margin-top:100px;">
    <div class="col-sm-4 offset-4 text-center">
        <h1>Opinie naszych gości</h1>
    </div>
</div>
<div class="row text-center" style="margin-top:100px;">
    <div class="col-sm-10 offset-1">
        <div class="row">
        @foreach(var item in Model) {
                <div class="col-xl-1 col-md-2 col-sm-3">
                        <h4>@Html.DisplayFor(modelItem => item.Autor)</h4><br />
                        <h4>@Html.DisplayFor(modelItem => item.Ocena) / 5</h4><br />
                        <h6>@Html.DisplayFor(modelItem => item.Opinia)</h6>

                </div>
        }
        </div>
    </div>
</div>
<div class="row text-center" style="margin-top:100px;">
    <div class="col-xl-3 col-lg-4 col-md-5 col-sm-6" style="margin:auto;">
        <a class="nav-link text-light" asp-area="" asp-controller="Opinies" asp-action="Create">
            <div class="przycisk"><h2>Podziel się swoją opinią</h2></div>
        </a>
    </div>
</div>

Views/Opinies/Create.cshtml
@model GofromaniaWebApp.Models.Opinie

@{
    ViewData["Title"] = "Create";
}



<div class="row">
    
    <div class="col-md-4 text-center" style="margin:auto;">
        <h1>Podziel się swoją opinią</h1>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ocena" class="control-label"></label>
                <input asp-for="Ocena" class="form-control" max="5" min="1" />
                <span asp-validation-for="Ocena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opinia" class="control-label"></label>
                <input asp-for="Opinia" class="form-control"/>
                <span asp-validation-for="Opinia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Ip" class="form-control" hidden value="0"/>
                <span asp-validation-for="Ip" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Aktwyne" value="false" hidden/>
                </label>
            </div>
            <div class="form-group">
                <input asp-for="Admin" class="form-control" hidden value="0" />
                <span asp-validation-for="Admin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Dodaj opinie" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 text-center">
        Twoja opinia będzie widoczna po zaakceptowaniu
    </div>
</div>
<div class="text-center">
    <a asp-action="ActiveOpinies">Powrót do strony głównej</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Opinies/Delete.cshtml
@model GofromaniaWebApp.Models.Opinie

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Opinie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ocena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ocena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Opinia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Opinia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aktwyne)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aktwyne)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Admin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Admin)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Opinies/Details.cshtml
@model GofromaniaWebApp.Models.Opinie

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Opinie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ocena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ocena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Opinia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Opinia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aktwyne)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aktwyne)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Admin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Admin)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Opinies/Edit.cshtml
@model GofromaniaWebApp.Models.Opinie

@{
    ViewData["Title"] = "Edit";
}
<h1>Edit</h1>
<h4>Opinie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Ocena" class="control-label"></label>
                <input asp-for="Ocena" class="form-control" />
                <span asp-validation-for="Ocena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opinia" class="control-label"></label>
                <input asp-for="Opinia" class="form-control" />
                <span asp-validation-for="Opinia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Ip" class="form-control" hidden />
                <span asp-validation-for="Ip" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Aktwyne" /> @Html.DisplayNameFor(model => model.Aktwyne)
                </label>
            </div>
            <div class="form-group">
                <input asp-for="Admin" class="form-control" value="@ViewBag.userid" hidden />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Opinies/Index.cshtml
@model IEnumerable<GofromaniaWebApp.Models.Opinie>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ocena)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Opinia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ip)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aktwyne)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Admin)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ocena)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Opinia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Aktwyne)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Admin)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GofromaniaWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GofromaniaWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Opinies" asp-action="ActiveOpinies"><img src="~/img/logo.png" height="50"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Opinies" asp-action="ActiveOpinies">Home</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GofromaniaWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>